image: docker:stable

services:
  - docker:dind

before_script:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD

stages:
  - build

build-image:
  stage: build
  script:
    - docker build --tag flaskapi .
    - docker tag flaskapi jesherpinkman/flaskapi:latest
    - docker push jesherpinkman/flaskapi:latest